version: "3.9" # versão do Docker

services: # grupo de containers
  database: # cria um container para o banco de dados
    image: postgres # define a imagem do banco de dados
    container_name: ignitenodejsiniciandoapidatabase # define o nome para o usuário
    # restart: always # faz o container executar assim que o Dokcer iniciar
    ports: # define as portas
      - 5432:5432 # para o banco de dados
    environment: # cria variavéis ambiente
      - POSTGRES_USER=ignitenodejsiniciandoapi
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ignitenodejsiniciandoapidatabase
    volumes: # define a criação do volume
      - pgdata:/data/postgres # define um nome e local

  app: # cria um container
    build: . # define que a aplicação será a imagem
    container_name: ignitenodejsiniciandoapiapp # define o nome para o usuário
    ports: # define as postas de execução
      - 3333:3333 # porta da aplciação
      - 9229:9229 # porta para o debug
    volumes: # define a criação do volume
      - .:/usr/app
    links: # cria um vinculo com outro container
      - database
    depends_on: # define que dependemos deste container para o funcionamento
      - database

volumes: # realiza configurações extra nos volumes
  pgdata: # define o tipo do driver do volume
    driver: local
